# Site settings
title: "Mariana Arboleda CV"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Mariana Arboleda"
resume_title:                   "PhD Student | Data Science Education"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "marianaarboleda@uninorte.edu.co"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+57 3172933325"
resume_contact_address:         "79B Street #42 - 262, Apartment 3B, Laure Building, Barranquilla"

resume_header_contact_info:     "marianaarboleda@uninorte.edu.co"
display_header_contact_info:    "true"

# resume_header_intro: "<p align='justify'>I am a DevOps Engineer with 2 years of experience designing and implementing CI/CD pipelines for a technology migration project from on-premise installations to AWS cloud using Azure DevOps. I have experience in implementing all stages of the DevOps cycle, including code integration, static analysis, dependency checks, compilation, packaging, and artifact repository publication. I have also configured the deployment stages in development, certification, and production environments, implemented acceptance, performance, and end-to-end testing, and managed the rollback stage.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:                            true
resume_section_teaching_experience:                   true
resume_section_education:                             true
resume_section_publications:                          true
resume_section_presetations:                          true
resume_section_outreach_and_professional_development: true
resume_section_development:                           true
resume_section_projects:                              false
resume_section_proeficient_in:                        false
resume_section_recognition:                           true
resume_section_links:                                 false
resume_section_associations:                          false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/marianaarboleda"
  resume_twitter_url:           "http://twitter.com/marbolf"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/sebastianvalenciasierra"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://marianaarboleda.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
  resume_download_url:          "https://marianaarboleda.github.io/hoja_de_vida/"
  resume_spanish_url:           "https://marianaarboleda.github.io/hoja_de_vida/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
